// Code generated by goctl. DO NOT EDIT.
package types

type StravaCallbackReq struct {
	Error string `form:"error,optional"`
	State string `form:"state,optional"`
	Code  string `form:"code,optional"`
}

type StravaCallbackResp struct {
}

type Request struct {
}

type Response struct {
}
